import { MERN_Stack_Courses } from './mern-stack-courses-model';

export const MERN_COURSES: MERN_Stack_Courses[] = [
  {
    mern_id: '0',
    mern_course_rating: '5',
    mern_course_name: 'MERN Stack Front To Back: Full Stack React, Redux & Node.js',
    mern_course_intro: 'Build and deploy a social network with Node.js, Express, React, Redux & MongoDB.',
    mern_course_instructor_intro: 'Harry John - Assistant Prof @ University of Calgary', 
    mern_course_outline: '-',
    mern_course_prereq: 'Object Oriented Programming',
    mern_no_of_lectures: 40,
    mern_no_of_hours: 40,
    mern_no_of_quizes: 5,
    mern_no_of_exercises: 5,
    mern_course_price: 100,
    mern_discount_on_course: 10,
    mern_date_aded: 'September 10, 2019',
    mern_student_enrolled_in_course: 200,
    mern_course_poster_path: 'https://www.google.com/search?q=mern+images&rlz=1C1CHBD_enPK927PK927&sxsrf=ALeKk00mWtnZcViZiP4WanDc53lgc8Elpw:1622985437082&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiRtc_zi4PxAhXHTcAKHaM4C2kQ_AUoAXoECAEQAw#imgrc=3ANdmI4Y7sjgSM',
    mern_course_lang: 'English',
    mern_course_level: 'Beginner'
  },
  {
    mern_course_rating: '4',
    mern_id: '1',
    mern_course_name: 'MERN Stack React, Socket io, Next.js Express,MongoDb, Nodejs',
    mern_course_intro: 'Build a socialMedia with MERN- React, Nextjs, socket io for realTime chat & Notifications, Infinite Scroll & much more..',
    mern_course_instructor_intro: 'Liza Enn - Associate Prof. @ Stanford University', 
    mern_course_outline: '-',
    mern_course_prereq: 'Database Systems',
    mern_no_of_lectures: 50,
    mern_no_of_hours: 50,
    mern_no_of_quizes: 6,
    mern_no_of_exercises: 6,
    mern_course_price: 90,
    mern_discount_on_course: 5,
    mern_date_aded: 'September 12, 2020',
    mern_student_enrolled_in_course: 30,
    mern_course_lang: 'French',
    mern_course_level: 'Intermediate',
    mern_course_poster_path: 'https://www.google.com/search?q=mern+images&rlz=1C1CHBD_enPK927PK927&sxsrf=ALeKk00mWtnZcViZiP4WanDc53lgc8Elpw:1622985437082&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiRtc_zi4PxAhXHTcAKHaM4C2kQ_AUoAXoECAEQAw#imgrc=ZdeR_M1_xFj8DM'
  },
  {
    mern_course_rating: '3',
    mern_id: '2',
    mern_course_name: 'MERN Stack React Node Ecommerce from Scratch to Deployment',
    mern_course_intro: 'MERN Stack React Node MongoDB powered E-Commerce App with PayPal and Credit Card Payment along with Admin Dashboard',
    mern_course_instructor_intro: 'Harry Potter - Associate Prof @ New York University', 
    mern_course_outline: '-',
    mern_course_prereq: 'None',
    mern_no_of_lectures: 12,
    mern_no_of_hours: 12,
    mern_no_of_quizes: 5,
    mern_no_of_exercises: 5,
    mern_course_price: 80,
    mern_discount_on_course: 3,
    mern_date_aded: 'December 10, 2019',
    mern_student_enrolled_in_course: 300,
    mern_course_lang: 'Urdu',
    mern_course_level: 'Expert',
    mern_course_poster_path: 'https://www.google.com/search?q=mern+images&rlz=1C1CHBD_enPK927PK927&sxsrf=ALeKk00mWtnZcViZiP4WanDc53lgc8Elpw:1622985437082&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiRtc_zi4PxAhXHTcAKHaM4C2kQ_AUoAXoECAEQAw#imgrc=t8usaOQZhMh6cM'
  }
];
